### ISSUE TITLE
imfuse: ERROR: Error while cutting images

### ISSUE THREAD

**Issue by holgerd001** [mviereck/microscopy-tools#3] opened 2021-02-04 08:36 UTC
imfuse v0.6.0-beta 
If I used resized images, I got the message "ERROR: Error while cutting images".

1. aligning images with align_image_stack -C -v -c40 --use-given-order <list of files>

2. imfuse -o imfu_diffr2clo2x2_soft25_less5.tif --cache --diffstat=r2,close2x2 --soft=25 --less=5 aligned_C_m_c40_order_00??.tif 
--> it works

3. resizing files: for file in aligned_C_m_c40_order_00*.tif; do convert $file -resize 20% pc20-$file; done

4. checking files with gwenview: no problems visible

5. imfuse -o imfu_diffr2clo2x2_soft25_less5.tif --cache --diffstat=r2,close2x2 --soft=25 --less=5 pc20-aligned_C_m_c40_order_00??.tif causes error:
--soft '25' --lessthanmax '5' --output '/mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/cache.imfuse/imfuseimfuse.diffstat=r2-close2x2-median-mean_soft25_less5_bg=enfuse.151832.tif' --
magick: insufficient image data in file `/mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/cache.imfuse/montage-diffstat-soft25-less5.98d67c.tif' @ error/tiff.c/ReadTIFFImage/1774.
imfuse ERROR: Error while cutting images

6. using enfuse: enfuse -o xD2030892_pc20-aligned_C_m_c40_order_grayl-star.tif --exposure-weight=0 --saturation-weight=0 --contrast-weight=1 --hard-mask --gray-projector=l-star <list of files>
--> it works 

Greetings
Holger

**Comment by mviereck** [comment] 2021-02-04 12:08
I've reproduced all steps and could not reproduce the issue, sorry.
Not sure what is going wrong.

You are using option `--cache`. Maybe something get wrong one time, and now a broken image is stored in cache.
Could you please remove `cache.imfuse` and try again?

I've made an update that gives some more messages about the progress.
Also it helps to run with `--verbose` to see in detail at which point the progress stops.

**Comment by holgerd001** [comment] 2021-02-04 14:30
> You are using option `--cache`. Maybe something get wrong one time, and now a broken image is stored in cache.
> Could you please remove `cache.imfuse` and try again?
Ok, now there is no folder made by imfuse.

> I've made an update that gives some more messages about the progress.
> Also it helps to run with `--verbose` to see in detail at which point the progress stops.
1. got the newest version (imfuse v0.6.1-beta)
2. starting imfuse: imfuse -o imfu_diff_pc20.tif --diffstat --verbose pc20-aligned_C_m_c40_order_00??.tif
3. It does'nt work: Error while flattening images
[Error while flattening images.txt](https://github.com/mviereck/microscopy-tools/files/5926290/Error.while.flattening.images.txt)

4. I took only 3 files for input, but the result was the same. "magick: insufficient image data in file `/mnt/Daten/holger/Fotos/stacks/20210203_Motte4_Kopf_Mikroskopobj/cache.imfuse/montage-diffstat.8f1e91.tif' @ error/tiff.c/ReadTIFFImage/1774.
imfuse ERROR: Error while flattening images"

Here are the files: 
[pc20-aligned_C_m_c40_order_000x.zip](https://github.com/mviereck/microscopy-tools/files/5926353/pc20-aligned_C_m_c40_order_000x.zip)

**Comment by mviereck** [comment] 2021-02-04 17:19
Likely the error depends on the version of ImageMagick.
I have three versions available:
```
$ magick --version
Version: ImageMagick 7.0.10-13 Q16 x86_64 2020-05-17 https://imagemagick.org
$ convert --version
Version: ImageMagick 6.9.11-24 Q16 x86_64 20200718 https://imagemagick.org
$ convert --version
Version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
```
It runs well with v7.0.10. I got a different error than yours with v6.9.11. (fixed now)
What is your version?

I assume that this command creating a transparent image is failing:
```
nice convert -size 899x597 xc:blue -transparent blue -type TrueColorAlpha +repage -quality 100% -compress lzw montage.tif
```
Could you check this command and its resulting image? Maybe the `-compress lzw` option fails and should be omitted.

Edit:
On the other hand, why does imfuse succeed with non-resized images? Where is the difference?
Just in case, I've added a note containing the command when transparent images are created.
The one with `montage` in the file name would be the failing image.

**Comment by holgerd001** [comment] 2021-02-05 07:24
> Likely the error depends on the version of ImageMagick.
> I have three versions available:
> 
> ```
> $ magick --version
> Version: ImageMagick 7.0.10-13 Q16 x86_64 2020-05-17 https://imagemagick.org
> $ convert --version
> Version: ImageMagick 6.9.11-24 Q16 x86_64 20200718 https://imagemagick.org
> $ convert --version
> Version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
> ```
> 
> It runs well with v7.0.10. I got a different error than yours with v6.9.11. (fixed now)
> What is your version?
I have:
~> magick --version
Version: ImageMagick 7.0.7-34 Q16 x86_64 20180520
~> convert --version
Version: ImageMagick 7.0.7-34 Q16 x86_64 20180520

In an other openSUSE repository I found version 7.0.10.53, but have not installed so far.

**Comment by mviereck** [comment] 2021-02-05 10:33
You have a quite recent version, ok. That should make a bug or different syntax in ImageMagick less likely.

I've changed the command to generate the transparent image a bit, and also added some verbose output around the point where the error occurs. Could you please try again?

**Comment by holgerd001** [comment] 2021-02-05 15:22
> nice convert -size 899x597 xc:blue -transparent blue -type TrueColorAlpha +repage -quality 100% -compress lzw montage.tif
> ```
> 
> Could you check this command and its resulting image? Maybe the `-compress lzw` option fails and should be omitted.
> 
I'm not familiar with convert an it's args, but here is what I done:
nice convert aligned_C_m_c40_order_0001.tif -size 899x597 xc:blue -transparent blue -type TrueColorAlpha +repage -quality 100% -compress lzw montage.tif
It shows the known warnings because of exif data. But it works as far as I can see.

nice convert pc20-aligned_C_m_c40_order_00??.tif -size 899x597 xc:blue -transparent blue -type TrueColorAlpha +repage -quality 100% -compress lzw montage.tif
No exif data = no warnings. It works.

But I don't know what the result (montage.tif) should look like.

**Comment by holgerd001** [comment] 2021-02-05 15:44
> I've changed the command to generate the transparent image a bit, and also added some verbose output around the point where the error occurs. Could you please try again?

1. starting imfuse using the shrunk images
imfuse -o imfu_morphologyr3_pc20_aligned_C_m_c40_order.tif --verbose --morphology=r3 pc20-aligned_C_m_c40_order_00??.tif

No errors, no warnings. And the result is ok too.

**Comment by mviereck** [comment] 2021-02-05 16:38
> No errors, no warnings. And the result is ok too.

So this seems to be fixed? Great! 
Thanks for your patience. I am grateful to get some feedback to the project.

**Comment by holgerd001** [comment] 2021-02-05 16:54
> So this seems to be fixed? Great!
Yes!

> Thanks for your patience.
Patience? You are very fast in bug fixing.

**Closed as completed** 2021-02-05 18:16 UTC

**Comment by holgerd001** [comment] 2021-02-18 14:42
I got it again:

~>imfuse --verbose --dog --less --close --finalblur=w47,s2 --alpha --threshold=50 --bg=enfuse aligned_C_c60_m_order_00??.tif    

imfuse: --bg: enfuse enfuse

...

imfuse: Montage 27/64. Duration: 00:13:03; ETA: 00:17:53
magick: no images for write '-write' 'mpr:lessthanmax' at CLI arg 60 @ error/operation.c/CLINoImageOperator/4882.
imfuse ERROR: Error while cutting images

imfuse: Montage 28/64. Duration: 00:13:09; ETA: 00:16:54

[Error while cutting images_20210218.zip](https://github.com/mviereck/microscopy-tools/files/6003524/Error.while.cutting.images_20210218.zip)

imfuse v0.6.7.0-beta
Version: ImageMagick 7.0.10-53 Q16 x86_64

**Comment by mviereck** [comment] 2021-02-18 14:51
Quite odd.
It happend in step 27/64, so the command already succeeded several times before failing.

Do you still have the `cache.imfuse` folder?
Please check image `/mnt/Daten/holger/Fotos/stacks/20210207_Fliege_Kopf_gelb_Mikroskopobj/cache.imfuse/lessthanmax.tif`. This is the image loaded for the failed `-write mpr:lessthanmax` command.

**Comment by holgerd001** [comment] 2021-02-18 14:55
> t happend in step 27/64, so the command already succeeded several times before failing.

Ah, perhaps that's the problem. I started imfuse two times in the same folder.
If there can be only one `cache.imfuse` folder, ...

>Do you still have the cache.imfuse folder?

No. 
There is one folder `cache.imfuse`, but it belongs to an other process of imfuse.

**Comment by mviereck** [comment] 2021-02-18 14:57
Ok, yes, that it is.
If you want to run a second instance, you can specify another cache folder, e.g. `--cache=cache2`.

**Comment by holgerd001** [comment] 2021-02-18 14:59
> you can specify another cache folder, e.g. `--cache=cache2`.

Ok, I try it.
